django/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

import core.urls
import user.urls

MEDIA_FILE_PATHS = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(user.urls, namespace='user')),
    path('', include(core.urls, namespace='core')),

] + MEDIA_FILE_PATHS

django/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('movies', views.MovieList.as_view(), name="MovieList"),
    path('movies/top', views.TopMovies.as_view(), name="TopMovies"),
    path('movie/<int:pk>', views.MovieDetail.as_view(), name="MovieDetail"),
    path('movie/<int:movie_id>/vote', views.CreateVote.as_view(), name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>', views.UpdateVote.as_view(), name='UpdateVote'),
    path('movie/<int:movie_id>/image/upload', views.MovieImageUpload.as_view(), name='MovieImageUpload'),
    path('person/<int:pk>', views.PersonDetail.as_view(), name='PersonDetail'),
]

django/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth import urls

from user import views

app_name = 'user'
urlpatterns = [
    path('register', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

django/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head >
  <meta charset="UTF-8" >
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no"
  >
  <link
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
    integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
    rel="stylesheet"
    crossorigin="anonymous"
  >
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>  <title >
    {% block title %}MyMDB{% endblock %}
  </title>
  <style >
    .mymdb-masthead {
      background-color: #EEEEEE;
      margin-bottom: 1em;
    }

    .errorlist {
      color: #e11;
    }
    .movie-image img {
      max-height: 10em;
      max-width: 10em;
    }

    .mymdb-sidebar > div {
      margin-bottom: 1em;
    }
  </style >

</head >
<body >
<div class="mymdb-masthead">
  <div class="container">
    <nav class="nav">
      <div class="navbar-brand">MyMDB</div>
      <a
        class="nav-link"
        href="{% url 'core:MovieList' %}"
      >
        Movies
      </a>
      <a href="{% url 'core:TopMovies' %}" class="nav-link">Top 10 Movies</a>
      {% if request.user.is_authenticated %}
        <a
            class="nav-link"
            href="{% url 'user:logout' %}"
        >
          Log out
        </a>
      {% else %}
        <a
            class="nav-link"
            href="{% url 'user:login' %}"
        >
          Log in
        </a>
        <a
            class="nav-link"
            href="{% url 'user:register' %}"
        >
          Register
        </a>

      {% endif %}
    </nav>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-8 mymdb-main">
     {% block main %}{% endblock %}
    </div>
    <div
        class="col-sm-3 offset-sm-1 mymdb-sidebar"
    >
      {% block sidebar %}{% endblock %}
    </div>
  </div>
</div>

</body >
</html >